package org.openmastery.publisher.api.metrics;

public enum MetricType {

	CAPACITY_DISTRIBUTION,
	MAX_WTFS_PER_DAY, HAYSTACK_SIZE, RESOLUTION_TIME, MAX_EXPERIMENT_CYCLE_COUNT, MAX_HUMAN_CYCLE_RATIO;

}
