package org.openmastery.publisher.api.metrics;

public enum MetricType {

	CAPACITY_DISTRIBUTION,
	MAX_WTFS_PER_DAY, MAX_HAYSTACK_SIZE, MAX_RESOLUTION_TIME, MAX_EXPERIMENT_CYCLES, AVG_HUMAN_CYCLE_RATIOS;

}
